FormMaker/Controllers/FormController.cs
using FormMaker.Application.Services.Interfaces;
using FormMaker.Models;
using FormMaker.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FormMaker.Controllers
{
    public class FormController : Controller
    {
        private readonly AppDbContext db;
        private readonly ITableService tableService;

        public FormController(AppDbContext _db, ITableService _tableService)
        {
            db = _db;
            tableService = _tableService;
        }
        public IActionResult Index()
        {
            FormViewModel model = new FormViewModel() { forms = db.Forms.ToList() };

            return View(model);


        }
        //[HttpPost]
        public IActionResult Search(string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                return RedirectToAction("Index");
            }
            else
            {
                var forms = db.Forms.Where(x => x.Name.Contains(searchTerm)).ToList();
                FormViewModel model = new FormViewModel() { forms = forms };
                return View("Index", model);
            }
        }

        public IActionResult FormCreate(FormViewModel model)
        {
            if (!db.Forms.Any(x => x.Name == model.name))
            {
                Form form = new Form() { Name = model.name };
                Random rnd = new Random();
                form.tableName = $"Tbl_{rnd.Next(0, 1001)}_AutoGen";
                db.Forms.Add(form);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "این فرم وجود دارد");
                model.forms = db.Forms.ToList();
                return View("Index", model);
            }
        }
        public IActionResult Delete(int Id)
        {
            var form = db.Forms.Find(Id);
            var response = tableService.DropTable("dbo", form.tableName);
            if (response == 1)
            {
                if (form != null)
                {
                    db.Forms.Remove(form);
                    db.SaveChanges();
                }
                FormViewModel model = new FormViewModel() { forms = db.Forms.ToList() };
                model.sqlResponse = "جدول مربوط به فرم پاک شد";
                return View("Index", model);
            }
            else
            {
                if (form != null)
                {
                    db.Forms.Remove(form);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
        }
    }
}

FormMaker/Controllers/FormFieldController.cs
using Aspose.Cells;
using FormMaker.Application.Services.Implementations;
using FormMaker.Application.Services.Interfaces;
using FormMaker.Models;
using FormMaker.Utilities;
using FormMaker.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;

namespace FormMaker.Controllers
{
    public class FormFieldController : Controller
    {
        private readonly AppDbContext db;
        private readonly ITableService tableService;
        private readonly IReportService reportService;

        public FormFieldController(AppDbContext _db, ITableService _tableService, IReportService _reportService)
        {
            db = _db;
            tableService = _tableService;
            reportService = _reportService;
        }
        public IActionResult Index(int Id)
        {

            var formFields = db.FormFields.Where(f => f.formId == Id).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).ToList();
            var fields = db.Fields.ToList();
            FormFieldViewModel model = new FormFieldViewModel() { formFields = formFields, fields = fields, formId = Id };
            return View(model);
        }
        public IActionResult FormFieldCreate(FormFieldViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (db.FormFields.Any(x => x.fieldId == model.fieldId && x.formId == model.formId))
                {
                    ModelState.AddModelError("formFieldErr", "این فیلد وجود دارد");
                    model.fields = db.Fields.ToList();
                    model.formFields = db.FormFields.Where(f => f.formId == model.formId).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).ToList();
                    return View("Index", model);
                }
                else
                {
                    FormField formField = new FormField() { formId = model.formId, fieldId = model.fieldId };
                    db.FormFields.Add(formField);
                    db.SaveChanges();
                    var singleField = db.FormFields.Where(c => c.formId == formField.formId).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).FirstOrDefault(z => z.Id == formField.Id);
                    if (singleField != null)
                    {
                        var typeName = singleField.field.dataType.Name;
                        var columnDefination = singleField.field.Name;
                        switch (typeName.ToLower())
                        {
                            case "int":
                                columnDefination += " " + SD.sqlType_Int;
                                break;
                            case "string":
                                columnDefination += " " + SD.sqlType_Nvarchar;
                                break;
                            case "datetime":
                                columnDefination += " " + SD.sqlType_DateTime;
                                break;
                            case "bool":
                                columnDefination += " " + SD.sqlType_Bool;
                                break;
                            default:
                                break;
                        }
                        var tableName = formField.form.tableName;
                        FormFieldViewModel viewModel = new FormFieldViewModel();
                        viewModel.formFields = db.FormFields.Where(f => f.formId == singleField.formId).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).ToList();
                        viewModel.fields = db.Fields.ToList();
                        viewModel.formId = singleField.formId;
                        int response = tableService.CheckCreateOrAlterTable("dbo", tableName, columnDefination);
                        switch (response)
                        {
                            case 1:
                                viewModel.SqlMessage = $"Table {tableName} was successfully created with column {columnDefination}";
                                break;
                            case 2:
                                viewModel.SqlMessage = $"column {columnDefination} was added to table {tableName}";
                                break;
                            case 3:
                                viewModel.SqlMessage = $"table {tableName} already has column {columnDefination}";
                                break;

                            default:
                                break;
                        }

                        return View("Index", viewModel);
                    }
                    else
                    {
                        ModelState.AddModelError("err", "این فیلد وجود ندارد");
                        return View("Index", model);
                    }

                }
            }
            else
            {
                ModelState.AddModelError("err", "خطا در ثبت فیلد");
                model.fields = db.Fields.ToList();
                model.formFields = db.FormFields.Where(f => f.formId == model.formId).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).ToList();
                return View("Index", model);
            }
        }
        public IActionResult Delete(int Id)
        {
            var formField = db.FormFields.Include(x => x.form).Include(b => b.field).ThenInclude(a => a.dataType).FirstOrDefault(d => d.Id == Id);
            //var formFieldCount= db.FormFields.Where(f => f.formId == formField.formId).ToList().Count;
            var columnName = formField.field.Name;
            var tableName = formField.form.tableName;

            FormFieldViewModel model = new FormFieldViewModel();
            int response = tableService.CheckAndDropColumn("dbo", tableName, columnName);
            switch (response)
            {
                case 1:
                    model.SqlMessage = $"Table {tableName} was droped";
                    var field = db.FormFields.Find(Id);
                    db.FormFields.Remove(field);
                    db.SaveChanges();
                    break;
                case 2:
                    model.SqlMessage = $"{columnName} deleted from {tableName} table successfully";
                    var field2 = db.FormFields.Find(Id);
                    db.FormFields.Remove(field2);
                    db.SaveChanges();
                    break;
                case 3:
                    model.SqlMessage = "column doesn't exist";
                    break;
                case 4:
                    model.SqlMessage = "table doesn't exist";
                    break;

                default:
                    break;
            }

            model.formFields = db.FormFields.Where(f => f.formId == formField.formId).Include(x => x.form).Include(a => a.field).ThenInclude(b => b.dataType).ToList();
            model.fields = db.Fields.ToList();
            model.formId = formField.formId;
            return View("Index", model);
        }
        public IActionResult Preview(int Id)
        {
            var formFields = db.FormFields.Where(x => x.formId == Id).Include(x => x.form).Include(x => x.field).ThenInclude(a => a.dataType).ToList();
            if (formFields.Count > 0)
            {
                FormFieldViewModel model = new FormFieldViewModel() { formFields = formFields };
                model.formId = Id;
                return View(model);

            }
            else
            {
                FormFieldViewModel model = new FormFieldViewModel() { formFields = formFields, SqlMessage = "اطلاعاتی در این جدول نیست" };
                model.formId = Id;
                model.fields = db.Fields.ToList();
                return View("Index", model);
            }
        }
        public IActionResult SubmitForm(int formId, List<string> values)
        {
            if (values != null && values.Count > 0)
            {

                string vals = "";
                string fields = "";
                var form = db.Forms.FirstOrDefault(x => x.Id == formId);
                if (form == null)
                {
                    return NotFound();
                }

                var formFields = db.FormFields.Where(x => x.formId == formId).Include(b => b.form).Include(x => x.field).ThenInclude(a => a.dataType).ToList();

                for (int i = 0; i < values.Count; i++)
                {
                    if (i == values.Count - 1)
                    {
                        vals += "N'" + values[i] + "'";
                    }
                    else
                    {
                        vals += "N'" + values[i] + "', ";

                    }
                }
                for (int i = 0; i < formFields.Count; i++)
                {
                    if (i == formFields.Count - 1)
                    {
                        fields += formFields[i].field.Name;
                    }
                    else
                    {
                        fields += formFields[i].field.Name + ", ";

                    }
                }
                var response = tableService.InsertToTableDynamic(form.tableName, fields, vals);
                var message = response == 1 ? "Data inserted successfully" : "Insertion failed";
                FormFieldViewModel model = new FormFieldViewModel() { formFields = formFields, formId = formId, SqlMessage = message };
                return View("Preview", model);
            }
            else
            {
                var formFields = db.FormFields.Where(x => x.formId == formId).ToList();
                FormFieldViewModel model = new FormFieldViewModel() { formFields = formFields, formId = formId, SqlMessage = "تمام فیلدها اجباریست" };
                return View("Preview", model);
            }
        }

FormMaker/Views/Shared/_FieldGrid.cshtml
@model FormMaker.ViewModels.FormViewModel
<table class="table table-bordered table-striped" style="direction:rtl">
    <thead>
        <tr>
            <td>ردیف</td>
            <td>نام فرم</td>
            <td>فیلد</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @if (Model.forms.Count > 0 )
        {
            @for (int i = 0; i < Model.forms.Count; i++)
            {
                <tr>
                    <td>@(i+1)</td>
                    <td>@Model.forms[i].Name</td>
                    <td class="text-center"><a class="btn btn-secondary" asp-action="Index" asp-controller="FormField" asp-route-Id="@Model.forms[i].Id"><i class="bi bi-list-check"></i></a></td>
                    <td class="text-center"><a class="btn btn-danger" asp-action="Delete" asp-route-Id="@Model.forms[i].Id">Delete</a></td>

                </tr>
            }
        }
        else
        {
            <tr>
                <td>اطلاعاتی وجود ندارد</td>
            </tr>
        }
    </tbody>
</table>

FormMaker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FormMaker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FormMaker.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FormMaker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Index">ثبت فرم</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FormMaker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>